Migrate to 4.0.0
tradingview/lightweight-charts-android pull request #129
Opened 2023-03-27 10:41 UTC by klee0kai

# Migrate to 4.0.0

## API updates by doc changes

- AreaStyleOptions: added invertFilledArea, crosshairMarkerBorderWidth
- BaselineStyleOptions: added lineType, crosshairMarkerBorderWidth
- removed SeriesSpecificOptions
- AreaSeriesOptions: changed 
- BaselineSeriesOptions: changed 
- CandlestickSeriesOptions: removed overlay, scalMargins
- HandleScaleOptions: removed axisFloatClickReset, added axisDoubleClickReset
- new AxisPressedMouseMoveOptions model 
- HistogramSeriesOptions: removed overlay, scaleMargins
- LayoutOptions backgroundColor changed to background
- LineSeriesOptions: removed overlay, scaleMargins
- PriceScaleOptions: drawTicks changed to ticksVisible
- TimeScaleOptions: aded ticksVisible
- LineType: added curved 
- added AreaData and BaselineData
- serial options moved to pricescale options. [details](https://tradingview.github.io/lightweight-charts/docs/migrations/from-v3-to-v4#scalemargins-option-has-been-removed-from-series-options)

## Demo updates 

- added timescale demo.  
- added pricescale demo.
- implement new chart types for demo. 
- implement loading historical data for demo

2023-03-27 13:48 UTC, klee0kai commented on app/build.gradle
> +//    implementation 'com.tradingview:lightweightcharts:3.8.0'
remove comment, set to 4.0.0 after publish

2023-03-29 10:55 UTC, makedonsky94 requested changes

2023-03-29 14:36 UTC, klee0kai commented on lightweightlibrary/lib/app/service-locator/locator.js
> +window.locator = Locator
Only for debug reason. 

For future i'd like use window.locator instead of window.chart.

2023-03-29 14:41 UTC, klee0kai commented on lightweightlibrary/src/main/java/com/tradingview/lightweightcharts/api/options/models/LayoutOptions.kt
> -    var backgroundColor: IntColor? = null,
backgroundColor [fully removed](https://tradingview.github.io/lightweight-charts/docs/migrations/from-v3-to-v4#backgroundcolor-from-layout-options-has-been-removed) from lib.

If we wanna save this field, it is well be long difficult way with hooks and additional data mapping to js code. 
So i thing better way migrate to original [doc](https://tradingview.github.io/lightweight-charts/docs/api) one to one

2023-03-30 09:26 UTC, klee0kai commented on lightweightlibrary/lib/app/chart-registration-functions-controller.js
> +        seriesFunctionManager.register();
done

2023-03-30 09:26 UTC, klee0kai commented on lightweightlibrary/lib/app/price-scale/price-scale-cache.js
> +export default class PriceScaleCache extends Map {
done

2023-03-30 09:26 UTC, klee0kai commented on lightweightlibrary/lib/app/price-scale/price-scale-creation.js
> +    constructor(locator,) {
done

2023-05-03 18:47 UTC, makedonsky94 approved these changes

2023-05-03 18:47 UTC, merged